mode: ContinuousDeployment

branches:
  main:
    increment: Minor
    regex: ^main$
    tag: ''
  feature:
    regex: ^feature/
    increment: Patch
    tag: beta
  release:
    regex: ^release/
    increment: Patch
    tag: rc
  hotfix:
    regex: ^hotfix/
    increment: Patch
    tag: hotfix