mode: ContinuousDeployment
branches:
  main:
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    regex: ^main$
    tag: ''
  feature:
    regex: ^feature/
    increment: Patch
    tag: beta
  release:
    regex: ^release/
    increment: Patch
    tag: rc
  hotfix:
    regex: ^hotfix/
    increment: Patch
    tag: hotfix