mode: ContinuousDeployment

branches:
  main:
    regex: ^main$
    increment: Minor
    label: ''

  feature:
    regex: ^feature/
    increment: Patch
    label: beta

  release:
    regex: ^release/
    increment: Patch
    label: rc

  hotfix:
    regex: ^hotfix/
    increment: Patch
    label: hotfix