name: ContinuousDeployment
branches:
  main:
    versioning-mode: MajorMinorPatch
    commit-message-incrementing: Enabled
    prevent-increment-of-merged-branch-version: true
    regex: ^main$
    tracks-release-branches: true
    is-release-branch: true
  feature:
    versioning-mode: ContinuousDelivery
    regex: ^feature/
    increment: Patch
    tag: beta
  release:
    versioning-mode: ContinuousDelivery
    regex: ^release/
    increment: Minor
    tag: rc
  hotfix:
    versioning-mode: ContinuousDelivery
    regex: ^hotfix/
    increment: Patch
    tag: hotfix