mode: ContinuousDeployment

branches:
  main:
    regex: ^main$
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    is-mainline: true
    label: ''

  feature:
    regex: ^feature/
    increment: Patch
    label: beta

  release:
    regex: ^release/
    increment: Patch
    label: rc

  hotfix:
    regex: ^hotfix/
    increment: Patch
    label: hotfix