mode: Mainline
commit-message-incrementing: Enabled
branches:
  main:
    increment: Minor
    regex: ^main$
  feature:
    regex: ^feature/
    increment: Patch
    tag: beta
  release:
    regex: ^release/
    increment: Patch
    tag: rc
  hotfix:
    regex: ^hotfix/
    increment: Patch
    tag: hotfix