name: Build and Release Library

on:
  push:
    # paths:
    #   - Soms.Shared.Cors/**
    branches:
      - main
      - release/*
      - hotfix/*
      - feature/*
      

permissions:
  contents: write  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.x'
          preferLatestVersion: true

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1
        with:
          useConfigFile: true
          configFilePath: './.github/version.yml'  

      - name: Print GitVersion Outputs
        run: |
          echo "GitVersion SemVer: ${{ steps.gitversion.outputs.SemVer }}"
          echo "GitVersion FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack Soms.Shared.Cors/Soms.Shared.Cors.csproj \
            --configuration Release \
            --output ./artifacts \
            /p:PackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

      - name: Push to NuGet (nuget.org)
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.gitversion.outputs.MajorMinorPatch }} 
          name: Release ${{ steps.gitversion.outputs.semVer }}
          body: |
            ## Release Notes
            - Release version: ${{ steps.gitversion.outputs.MajorMinorPatch }}
            - Release date: ${{ steps.gitversion.outputs.CommitDate }}
            - Release commit: ${{ github.sha }}
            - Release SemVer: ${{ steps.gitversion.outputs.SemVer }}
            - Release FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
          files: ./artifacts/*.nupkg