name: Build and Release Library

on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*
      - feature/*
    tags:
      - 'v*'

permissions:
  contents: write  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack Soms.Shared.CORS/Soms.Shared.CORS.csproj \
            --configuration Release \
            --output ./artifacts \
            /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Push to NuGet (nuget.org)
        run: dotnet nuget push ./artifacts/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
        if: github.ref_type == 'tag'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          name: Release ${{ steps.gitversion.outputs.semVer }}
          files: ./artifacts/*.nupkg
        if: github.ref_type == 'tag'